import type { CategoryConfig } from "./catalog-types";

const tireBrands = ["Michelin", "Bridgestone", "Goodyear", "Pirelli", "Continental", "BFGoodrich"];
const wheelBrands = ["Enkei", "BBS", "OZ Racing", "Konig", "Motegi", "American Racing"];

export const URL_SLUG_MAP: Record<string, string> = {
  "all-season-tires": "all-season",
  "summer-tires": "summer",
  "winter-tires": "winter",
  "performance-tires": "performance",
  "alloy-wheels": "alloy-wheels",
  "steel-wheels": "steel-wheels",
  "tire-wheel-packages": "packages",
  "wheel-accessories": "wheel-accessories",
  "tire-accessories": "tire-accessories",
};

export const CONFIG_TO_URL_SLUG: Record<string, string> = Object.fromEntries(
  Object.entries(URL_SLUG_MAP).map(([url, config]) => [config, url])
);

export function getUrlSlug(configSlug: string): string {
  return CONFIG_TO_URL_SLUG[configSlug] ?? configSlug;
}

export function getConfigKey(urlSlug: string): string | undefined {
  return URL_SLUG_MAP[urlSlug];
}

export const CATEGORY_CONFIGS: Record<string, CategoryConfig> = {
  "all-season": {
    name: "all-season",
    slug: "all-season",
    title: "All-Season Tires",
    subtitle: "Year-Round Versatility",
    description: "Engineered for balanced performance in dry, wet, and light snow conditions. Our all-season tires deliver confident handling, long tread life, and year-round peace of mind.",
    longDescription: "All-season tires are the most popular choice for everyday drivers who need reliable performance across varying conditions. They feature specialized tread compounds that remain flexible in cold weather while providing excellent wear characteristics in warmer months. Modern all-season tires incorporate advanced silica compounds, multi-directional siping, and optimized tread patterns to deliver confident traction whether you are commuting through rain showers or cruising on dry highways.",
    heroImage: "/categories/allseason.png",
    heroBgFrom: "from-blue-600",
    heroBgVia: "via-blue-800",
    heroBgTo: "to-indigo-900",
    seoTitle: "All-Season Tires | Premium Year-Round Performance | Tire&Wheel Mart",
    seoDescription: "Shop premium all-season tires from Michelin, Bridgestone, Goodyear, and more. Engineered for balanced dry, wet, and light snow traction with long tread life.",
    seoContent: [
      "All-season tires represent the pinnacle of tire versatility, engineered to deliver reliable performance across a wide range of driving conditions. Unlike dedicated summer or winter tires, all-season tires use advanced rubber compounds that maintain flexibility in colder temperatures while resisting wear in warmer weather, making them the ideal choice for drivers in moderate climates who want a single set of tires for year-round use.",
      "Modern all-season tires incorporate sophisticated tread patterns with variable-pitch sequencing to reduce road noise, circumferential grooves for hydroplaning resistance, and lateral siping for enhanced snow traction. Many premium models now feature silica-enriched compounds that improve wet grip without compromising rolling resistance, giving you both safety and fuel efficiency in one package."
    ],
    faq: [
      { question: "How long do all-season tires last?", answer: "Most all-season tires have a treadwear warranty between 60,000 and 80,000 miles. Actual lifespan depends on driving habits, road conditions, vehicle alignment, and proper tire maintenance including regular rotation and inflation checks." },
      { question: "Can I use all-season tires in snow?", answer: "All-season tires can handle light snow conditions thanks to their specialized tread compound and siping. However, for severe winter conditions or areas with heavy snowfall, dedicated winter tires provide significantly better traction and safety." },
      { question: "What is the difference between touring and performance all-season tires?", answer: "Touring all-season tires prioritize ride comfort, low noise, and long tread life. Performance all-season tires focus on higher speed ratings, sharper handling, and enhanced grip at the expense of some tread life and ride comfort." },
    ],
    buyingGuide: {
      title: "Choosing the Right All-Season Tires",
      description: "Selecting the perfect all-season tire depends on your driving needs, local climate, and vehicle type. Here is what to consider.",
      tips: [
        { title: "Consider Your Climate", description: "If you experience mild winters with light snow, standard all-season tires are sufficient. For frequent snow, look for all-weather tires with the Three-Peak Mountain Snowflake rating." },
        { title: "Match Speed Ratings", description: "Ensure the tire speed rating matches or exceeds your vehicle's capabilities. Higher-rated tires offer better high-speed performance but may wear faster." },
        { title: "Check Treadwear Warranty", description: "Compare treadwear warranties between brands. A 70,000-mile warranty indicates longer expected life but may use a harder compound that sacrifices some dry grip." },
      ],
      features: [
        { title: "Silica Compound", description: "Enhanced wet traction and reduced rolling resistance for better fuel economy." },
        { title: "Variable-Pitch Tread", description: "Reduces road noise for a quieter, more comfortable ride." },
        { title: "Circumferential Grooves", description: "Effectively channel water away to prevent hydroplaning." },
      ],
      recommendations: [
        { title: "Premium Choice", description: "Michelin CrossClimate 2 — Best-in-class all-season performance with severe snow rating.", link: "/category/all-season" },
        { title: "Best Value", description: "Continental PureContact LS — Excellent balance of comfort, handling, and tread life.", link: "/category/all-season" },
        { title: "Performance Pick", description: "Pirelli Cinturato P7 All Season Plus II — Sporty handling with long tread life.", link: "/category/all-season" },
      ],
    },
    featuredBrands: tireBrands,
    relatedCategories: ["summer", "winter", "performance"],
    ctaPrimary: { label: "Browse Collection", href: "#products" },
    ctaSecondary: { label: "View Buying Guide", href: "#buying-guide" },
  },
  summer: {
    name: "summer",
    slug: "summer",
    title: "Summer Tires",
    subtitle: "Maximum Warm-Weather Performance",
    description: "Engineered for exceptional dry and wet grip in warm conditions. Summer tires deliver precise handling, shorter braking distances, and ultimate driving confidence from spring through fall.",
    heroImage: "/categories/summertires.png",
    heroBgFrom: "from-red-600",
    heroBgVia: "via-red-800",
    heroBgTo: "to-rose-900",
    seoTitle: "Summer Tires | Ultra-High Performance | Tire&Wheel Mart",
    seoDescription: "Shop premium summer tires from leading brands. Experience superior dry and wet grip, precise handling, and high-speed stability for warm-weather driving.",
    faq: [
      { question: "Can I use summer tires in winter?", answer: "No. Summer tires are not designed for cold temperatures below 45°F. Their rubber compound hardens in cold weather, significantly reducing traction. Use winter tires or all-season tires in cold conditions." },
      { question: "Why do summer tires perform better on dry roads?", answer: "Summer tires use a softer rubber compound optimized for warm temperatures, combined with a tread pattern that maximizes contact patch area. This provides superior grip, shorter braking distances, and more precise steering response." },
      { question: "How long do summer tires last?", answer: "Summer tires typically last 20,000 to 40,000 miles depending on driving style and conditions. Their softer compound provides better grip but wears faster than all-season tires." },
    ],
    buyingGuide: {
      title: "Choosing Summer Tires",
      description: "Summer tires deliver the ultimate warm-weather driving experience. Here is what to consider when selecting your set.",
      tips: [
        { title: "Assess Your Driving", description: "Consider how you drive. Enthusiasts who push their cars on back roads need max performance summer tires. Daily drivers benefit from ultra-high-performance all-season alternatives." },
        { title: "Check Temperature Ratings", description: "Summer tires perform best above 45°F. Below this temperature, grip degrades rapidly and the tire becomes prone to cracking." },
        { title: "Consider Treadwear Ratings", description: "Lower treadwear ratings indicate softer compounds with more grip but shorter life. Balance your performance needs with expected mileage." },
      ],
      features: [
        { title: "High-Grip Compound", description: "Optimized for maximum adhesion in warm conditions." },
        { title: "Reinforced Sidewalls", description: "Improved cornering stability and steering response." },
        { title: "Asymmetric Tread", description: "Large outer blocks for dry grip, inner grooves for water evacuation." },
      ],
      recommendations: [
        { title: "Premium Choice", description: "Michelin Pilot Sport 4S — Benchmark summer performance tire.", link: "/category/summer" },
        { title: "Track Ready", description: "Pirelli P Zero Trofeo R — Extreme performance for track days.", link: "/category/summer" },
        { title: "Daily Driver", description: "Continental ExtremeContact Sport 02 — Excellent balance of grip and comfort.", link: "/category/summer" },
      ],
    },
    featuredBrands: tireBrands,
    relatedCategories: ["all-season", "performance", "winter"],
    ctaPrimary: { label: "Browse Collection", href: "#products" },
    ctaSecondary: { label: "View Buying Guide", href: "#buying-guide" },
  },
  winter: {
    name: "winter",
    slug: "winter",
    title: "Winter Tires",
    subtitle: "Ultimate Cold-Weather Safety",
    description: "Engineered for maximum traction on snow and ice. Winter tires keep you safe when temperatures drop below 45°F with specialized compounds and aggressive tread patterns.",
    heroImage: "/categories/wintertires.png",
    heroBgFrom: "from-gray-800",
    heroBgVia: "via-gray-900",
    heroBgTo: "to-black",
    seoTitle: "Winter Tires | Snow & Ice Traction | Tire&Wheel Mart",
    seoDescription: "Shop premium winter tires from top brands. Snow and ice rated with Three-Peak Mountain Snowflake certification for maximum cold-weather safety.",
    faq: [
      { question: "Are winter tires worth it?", answer: "Yes. Winter tires provide significantly better traction, braking, and handling in snow and ice compared to all-season tires. The specialized rubber compound stays flexible in cold temperatures, giving you more control and shorter stopping distances." },
      { question: "Can I drive with winter tires all year?", answer: "It is not recommended. Winter tires are made from softer compounds that wear rapidly in warm conditions. The tread pattern designed for snow also reduces dry-road performance and increases fuel consumption." },
      { question: "What does the Three-Peak Mountain Snowflake mean?", answer: "The Three-Peak Mountain Snowflake (3PMSF) symbol indicates the tire meets severe snow service requirements, providing enhanced traction in snow beyond standard winter tires." },
    ],
    buyingGuide: {
      title: "Choosing Winter Tires",
      description: "Winter tires are your most important safety investment for cold-weather driving. Here is what you need to know.",
      tips: [
        { title: "Studded vs Studless", description: "Studded tires provide maximum ice traction but are restricted in some areas. Studless winter tires use advanced compound technology for excellent snow and ice grip without metal studs." },
        { title: "Install a Full Set", description: "Always install winter tires on all four wheels for balanced handling and safety. Mixing tire types can create unpredictable handling characteristics." },
        { title: "Check the 3PMSF Rating", description: "Look for the Three-Peak Mountain Snowflake symbol, which indicates the tire meets severe snow service requirements." },
      ],
      features: [
        { title: "Cold-Weather Compound", description: "Stays flexible in freezing temperatures for maximum grip." },
        { title: "Deep Tread Depth", description: "More tread depth than summer tires for better snow traction." },
        { title: "Zig-Zag Siping", description: "Thousands of biting edges improve grip on ice and packed snow." },
      ],
      recommendations: [
        { title: "Premium Choice", description: "Michelin X-Ice Snow — Exceptional winter performance and long tread life.", link: "/category/winter" },
        { title: "Best Value", description: "Bridgestone Blizzak WS90 — Industry standard for snow and ice traction.", link: "/category/winter" },
        { title: "Performance Pick", description: "Pirelli Winter Sottozero 3 — High-performance winter tire for sporty vehicles.", link: "/category/winter" },
      ],
    },
    featuredBrands: tireBrands,
    relatedCategories: ["all-season", "summer", "performance"],
    ctaPrimary: { label: "Browse Collection", href: "#products" },
    ctaSecondary: { label: "View Buying Guide", href: "#buying-guide" },
  },
  performance: {
    name: "performance",
    slug: "performance",
    title: "Performance Tires",
    subtitle: "Engineered for the Enthusiast",
    description: "Designed for drivers who demand the ultimate in handling, grip, and high-speed stability. Performance tires deliver race-inspired technology for the road.",
    heroImage: "/categories/performancetires.png",
    heroBgFrom: "from-amber-600",
    heroBgVia: "via-amber-800",
    heroBgTo: "to-orange-900",
    seoTitle: "Performance Tires | Ultra-High Performance | Tire&Wheel Mart",
    seoDescription: "Shop ultra-high-performance tires from Michelin, Pirelli, and Continental. Race-inspired technology for superior grip, handling, and high-speed stability.",
    faq: [
      { question: "What is the difference between summer and performance tires?", answer: "Performance tires are a broader category that includes ultra-high-performance summer tires. They feature even softer compounds, enhanced sidewall construction, and aggressive tread patterns for maximum cornering grip and steering precision." },
      { question: "Are performance tires good for daily driving?", answer: "Yes, many modern performance tires offer excellent daily driving characteristics with acceptable ride comfort. However, they typically wear faster and have lower wet-weather performance than dedicated all-season touring tires." },
      { question: "What speed rating do I need?", answer: "Choose a speed rating that exceeds your vehicle's top speed. Common ratings include V (149 mph), W (168 mph), and Y (186 mph). Higher ratings indicate better high-speed capability but may compromise ride comfort." },
    ],
    buyingGuide: {
      title: "Choosing Performance Tires",
      description: "Performance tires transform your vehicle's capabilities. Here is what enthusiasts should consider.",
      tips: [
        { title: "Match to Your Vehicle", description: "Sports cars, sedans, and coupes each have different performance tire requirements. Consider your vehicle's weight, power output, and intended use." },
        { title: "Consider UTQG Ratings", description: "The Uniform Tire Quality Grade indicates treadwear, traction, and temperature resistance. Lower treadwear numbers mean softer compounds with more grip." },
        { title: "Check Sidewall Construction", description: "Performance tires often feature reinforced sidewalls for improved cornering stability. Look for XL or RF designations for enhanced load capacity." },
      ],
      features: [
        { title: "High-Speed Rated", description: "Engineered for stability at speeds exceeding 149 mph." },
        { title: "Aramid Reinforcement", description: "Lightweight, ultra-strong fibers for precise steering feel." },
        { title: "Heat-Dissipating Tread", description: "Advanced compounds manage heat buildup during aggressive driving." },
      ],
      recommendations: [
        { title: "Track Day Pick", description: "Michelin Pilot Sport Cup 2 R — Maximum grip for track driving.", link: "/category/performance" },
        { title: "Street Performance", description: "Continental ExtremeContact Sport — Outstanding dry and wet grip.", link: "/category/performance" },
        { title: "Grand Touring", description: "Pirelli P Zero All Season Plus — Performance with year-round capability.", link: "/category/performance" },
      ],
    },
    featuredBrands: tireBrands,
    relatedCategories: ["summer", "all-season", "alloy-wheels"],
    ctaPrimary: { label: "Browse Collection", href: "#products" },
    ctaSecondary: { label: "View Buying Guide", href: "#buying-guide" },
  },
  "alloy-wheels": {
    name: "alloy-wheels",
    slug: "alloy-wheels",
    title: "Alloy Wheels",
    subtitle: "Style Meets Performance",
    description: "Upgrade your vehicle's appearance and performance with precision-crafted alloy wheels. Lightweight, strong, and designed to make a statement.",
    heroImage: "/categories/alloywheels.webp",
    heroBgFrom: "from-red-600",
    heroBgVia: "via-red-700",
    heroBgTo: "to-rose-900",
    seoTitle: "Alloy Wheels | Premium Custom Rims | Tire&Wheel Mart",
    seoDescription: "Shop premium alloy wheels from Enkei, BBS, OZ Racing, and more. Lightweight performance wheels for every vehicle make and model.",
    faq: [
      { question: "What is the difference between alloy and steel wheels?", answer: "Alloy wheels are lighter, stronger, and offer better heat dissipation than steel wheels. They improve handling, acceleration, and braking while providing superior aesthetic options. Steel wheels are more durable and economical for winter use." },
      { question: "Will alloy wheels fit my vehicle?", answer: "Alloy wheels are manufactured with specific bolt patterns, offsets, and center bores for each vehicle. Check your vehicle's specifications including bolt pattern, offset, and hub bore to ensure proper fitment." },
      { question: "Do larger wheels affect ride quality?", answer: "Larger diameter wheels with lower-profile tires can reduce ride comfort and increase road noise. However, they provide sharper handling and a more aggressive appearance. Consider your priorities when choosing wheel size." },
    ],
    buyingGuide: {
      title: "Choosing Alloy Wheels",
      description: "Alloy wheels transform both the look and feel of your vehicle. Here is your guide to selecting the perfect set.",
      tips: [
        { title: "Understand Bolt Patterns", description: "Your vehicle's bolt pattern (e.g., 5x114.3) determines wheel compatibility. Never use adapters or modifications to fit incorrect patterns." },
        { title: "Consider Offset", description: "Wheel offset affects handling and clearance. Positive offset pushes wheels inward, negative offset creates a wider stance. Check your vehicle's specifications." },
        { title: "Choose the Right Size", description: "Larger wheels require lower-profile tires. Ensure the overall diameter matches your vehicle's specifications to maintain accurate speedometer readings." },
      ],
      features: [
        { title: "Flow Formed Construction", description: "Stronger and lighter than cast wheels for improved performance." },
        { title: "Corrosion Resistant", description: "Multi-layer clear coat protects against brake dust and road salt." },
        { title: "Precision Balanced", description: "Computer-balanced for vibration-free driving at any speed." },
      ],
      recommendations: [
        { title: "Performance Choice", description: "Enkei RPF1 — Lightweight, race-proven design for serious enthusiasts.", link: "/category/alloy-wheels" },
        { title: "Luxury Pick", description: "BBS CI-R — Premium German engineering with iconic design.", link: "/category/alloy-wheels" },
        { title: "Best Value", description: "Konig Hypergram — Excellent performance at an accessible price point.", link: "/category/alloy-wheels" },
      ],
    },
    featuredBrands: wheelBrands,
    relatedCategories: ["steel-wheels", "performance", "packages"],
    ctaPrimary: { label: "Browse Collection", href: "#products" },
    ctaSecondary: { label: "View Buying Guide", href: "#buying-guide" },
  },
  "steel-wheels": {
    name: "steel-wheels",
    slug: "steel-wheels",
    title: "Steel Wheels",
    subtitle: "Durable & Economical",
    description: "Built for durability and value. Steel wheels are the practical choice for winter tire sets, commercial vehicles, and budget-conscious drivers.",
    heroImage: "/categories/steelwheels.png",
    heroBgFrom: "from-gray-800",
    heroBgVia: "via-gray-900",
    heroBgTo: "to-black",
    seoTitle: "Steel Wheels | Durable & Affordable | Tire&Wheel Mart",
    seoDescription: "Shop durable steel wheels for winter tire sets, commercial vehicles, and budget-friendly replacements. Strong, reliable, and economical.",
    faq: [
      { question: "Are steel wheels stronger than alloy?", answer: "Steel wheels are generally more durable and can withstand more impact without cracking. However, they are heavier and more prone to bending. Alloy wheels are stronger in terms of strength-to-weight ratio." },
      { question: "Are steel wheels good for winter?", answer: "Absolutely. Steel wheels are the preferred choice for winter tire sets because they can withstand road salt and pothole impacts better than alloys. They are also more affordable, making them ideal for seasonal tire changes." },
      { question: "Can I use hubcaps on steel wheels?", answer: "Yes. Steel wheels are designed to accept hubcaps or wheel covers, allowing you to customize their appearance. Many vehicles come with factory wheel covers that snap onto steel wheels." },
    ],
    featuredBrands: ["Pro Comp", "American Racing", "Cragar", "D Window", "Mickey Thompson"],
    relatedCategories: ["alloy-wheels", "wheel-accessories", "tire-accessories"],
    ctaPrimary: { label: "Browse Collection", href: "#products" },
    ctaSecondary: { label: "View Steel Options", href: "#products" },
  },
  packages: {
    name: "packages",
    slug: "packages",
    title: "Tire & Wheel Packages",
    subtitle: "Perfectly Matched Sets",
    description: "Pre-configured tire and wheel packages mounted, balanced, and ready to install. Save time and money with perfectly matched sets from our experts.",
    heroImage: "/categories/tireandwheel.png",
    heroBgFrom: "from-gray-800",
    heroBgVia: "via-gray-700",
    heroBgTo: "to-gray-600",
    seoTitle: "Tire & Wheel Packages | Mounted & Balanced | Tire&Wheel Mart",
    seoDescription: "Shop pre-configured tire and wheel packages professionally mounted and balanced. Save on complete sets with expert-matched combinations.",
    faq: [
      { question: "What is included in a tire and wheel package?", answer: "Our packages include tires mounted on wheels, professionally balanced, and including TPMS sensors when applicable. Packages arrive ready to install on your vehicle." },
      { question: "Will you mount the tires on the wheels?", answer: "Yes. All packages come professionally mounted and computer-balanced by our certified technicians. Each package is inspected before shipping." },
      { question: "Can I return a package?", answer: "You can return unused, unmounted packages within 30 days. Once mounted on a vehicle, tires cannot be returned due to safety regulations." },
    ],
    featuredBrands: [...tireBrands.slice(0, 4), ...wheelBrands.slice(0, 3)],
    relatedCategories: ["all-season", "alloy-wheels", "summer"],
    ctaPrimary: { label: "Browse Packages", href: "#products" },
  },
  "wheel-accessories": {
    name: "wheel-accessories",
    slug: "wheel-accessories",
    title: "Wheel Accessories",
    subtitle: "Complete Your Setup",
    description: "Everything you need to install, maintain, and enhance your wheels. From lug nuts and center caps to TPMS sensors and wheel locks.",
    heroImage: "/categories/wheelaccessories.png",
    heroBgFrom: "from-red-600",
    heroBgVia: "via-red-700",
    heroBgTo: "to-rose-900",
    seoTitle: "Wheel Accessories | Lug Nuts, Center Caps & More | Tire&Wheel Mart",
    seoDescription: "Shop wheel accessories including lug nuts, center caps, TPMS sensors, wheel locks, spacers, and installation kits for your vehicle.",
    faq: [
      { question: "Do I need new lug nuts with aftermarket wheels?", answer: "Yes. Aftermarket wheels often require different lug nut styles. Alloy wheels typically need tapered or ball-seat lug nuts, while steel wheels use flat or shank-style nuts." },
      { question: "What is a TPMS sensor and do I need one?", answer: "A Tire Pressure Monitoring System sensor monitors tire pressure and alerts you when pressure drops. Most vehicles manufactured after 2007 require TPMS sensors. Check your vehicle compatibility." },
      { question: "How do I choose the right wheel spacers?", answer: "Select wheel spacers based on your bolt pattern, hub bore, and desired offset change. Use hub-centric spacers for proper fitment and to prevent vibration." },
    ],
    featuredBrands: ["Gorilla", "McGard", "Dorman", "ACDelco", "Mopar"],
    relatedCategories: ["tire-accessories", "alloy-wheels", "steel-wheels"],
    ctaPrimary: { label: "Browse Accessories", href: "#products" },
  },
  "tire-accessories": {
    name: "tire-accessories",
    slug: "tire-accessories",
    title: "Tire Accessories",
    subtitle: "Maintain & Protect",
    description: "Keep your tires in peak condition with our complete range of tire care accessories. From repair kits and gauges to covers and chains.",
    heroImage: "/categories/tireaccessories.png",
    heroBgFrom: "from-gray-800",
    heroBgVia: "via-gray-900",
    heroBgTo: "to-black",
    seoTitle: "Tire Accessories | Repair Kits, Gauges & Covers | Tire&Wheel Mart",
    seoDescription: "Shop tire accessories including repair kits, tire pressure gauges, tire covers, chains, and cleaning products for proper tire maintenance.",
    faq: [
      { question: "What should be in a tire repair kit?", answer: "A basic tire repair kit should include tire plugs, a reaming tool, plug insertion tool, rubber cement, and a portable air compressor or CO2 inflator. For emergencies, consider a complete roadside kit." },
      { question: "How often should I check tire pressure?", answer: "Check tire pressure at least once a month and before long trips. Tire pressure should be checked when tires are cold for the most accurate reading. The recommended pressure is listed on your vehicle's door placard." },
      { question: "Can I use tire chains on any tire?", answer: "Tire chains must be the correct size for your tire dimensions. Check your vehicle owner's manual for chain compatibility — some vehicles with limited clearance cannot use chains and may require cable-style traction devices." },
    ],
    featuredBrands: ["Slime", "Fix-A-Flat", "ARB", "Michelin", "NOCO"],
    relatedCategories: ["wheel-accessories", "all-season", "winter"],
    ctaPrimary: { label: "Browse Accessories", href: "#products" },
  },
};
