insert into public.leads (name, email, phone, company, status, source, notes, is_active) values
('James Thompson', 'james.thompson@email.com', '+1 (555) 101-0001', 'AutoParts Pro', 'converted', 'website', 'Purchased 4 tires - All-Season', true),
('Maria Garcia', 'maria.garcia@email.com', '+1 (555) 101-0002', null, 'qualified', 'referral', 'Looking for winter tires', true),
('Robert Chen', 'robert.chen@email.com', '+1 (555) 101-0003', 'Chen Logistics', 'new', 'website', 'Fleet quote needed - 6 vehicles', true),
('Sarah Johnson', 'sarah.j@email.com', '+1 (555) 101-0004', 'Johnson Auto', 'contacted', 'phone', 'Left voicemail - callback requested', true),
('Michael Brown', 'mbrown@email.com', '+1 (555) 101-0005', null, 'closed', 'walk-in', 'Not interested at this time', false),
('Emily Davis', 'emily.davis@email.com', '+1 (555) 101-0006', 'Davis Transport', 'converted', 'website', 'Bought 8 truck tires', true),
('David Wilson', 'dwilson@email.com', '+1 (555) 101-0007', 'Wilson Fleet Services', 'qualified', 'email', 'Requested quote for 12 vehicles', true),
('Jennifer Lee', 'jlee@email.com', '+1 (555) 101-0008', null, 'new', 'website', 'Shopping for SUV tires', true),
('Christopher Taylor', 'ctaylor@email.com', '+1 (555) 101-0009', 'Taylor Auto Group', 'contacted', 'referral', 'Interested in bulk pricing', true),
('Amanda Martinez', 'amanda.m@email.com', '+1 (555) 101-0010', 'Martinez Repair', 'converted', 'website', 'Regular customer - 3rd purchase', true),
('Daniel Anderson', 'danderson@email.com', '+1 (555) 101-0011', null, 'qualified', 'social', 'Instagram inquiry - performance tires', true),
('Jessica Thomas', 'jthomas@email.com', '+1 (555) 101-0012', 'Thomas Trucking', 'new', 'website', 'Needs tires for semi-truck fleet', true),
('William Jackson', 'wjackson@email.com', '+1 (555) 101-0013', null, 'contacted', 'phone', 'Price compare - Bridgestone vs Michelin', true),
('Ashley White', 'a.white@email.com', '+1 (555) 101-0014', 'White Automotive', 'converted', 'website', 'Bought winter tire package', true),
('Matthew Harris', 'mharris@email.com', '+1 (555) 101-0015', 'Harris Delivery', 'qualified', 'referral', 'Delivery van fleet - 5 vehicles', true),
('Brittany Martin', 'bmartin@email.com', '+1 (555) 101-0016', null, 'new', 'website', 'First time buyer - sedan tires', true),
('Joshua Robinson', 'jrobinson@email.com', '+1 (555) 101-0017', 'Robinson Construction', 'contacted', 'email', 'Needs tires for work trucks', true),
('Megan Clark', 'mclark@email.com', '+1 (555) 101-0018', null, 'closed', 'walk-in', 'Found cheaper elsewhere', false),
('Andrew Lewis', 'alewis@email.com', '+1 (555) 101-0019', 'Lewis Auto Sales', 'qualified', 'website', 'Used car lot - needs bulk tires', true),
('Lauren Walker', 'lwalker@email.com', '+1 (555) 101-0020', 'Walker Transport', 'converted', 'referral', 'Repeat customer - fleet tires', true),
('Kevin Hall', 'khall@email.com', '+1 (555) 101-0021', null, 'new', 'social', 'Facebook ad click - tire inquiry', true),
('Stephanie Allen', 'sallen@email.com', '+1 (555) 101-0022', 'Allen Trucking LLC', 'contacted', 'phone', 'Interested in fleet discount program', true),
('Brandon Young', 'byoung@email.com', '+1 (555) 101-0023', null, 'qualified', 'website', 'Performance tires for sports car', true),
('Nicole King', 'nking@email.com', '+1 (555) 101-0024', 'King Auto Body', 'converted', 'referral', 'Regular wholesaler - monthly orders', true),
('Tyler Wright', 'twright@email.com', '+1 (555) 101-0025', 'Wright Logistics', 'new', 'email', 'Quote for 18-wheeler tires', true),
('Samantha Hill', 'shill@email.com', '+1 (555) 101-0026', null, 'contacted', 'website', 'Comparing prices on SUV tires', true),
('Jacob Scott', 'jscott@email.com', '+1 (555) 101-0027', 'Scott Fleet Services', 'qualified', 'referral', 'Needs winter tires for company cars', true),
('Hannah Green', 'hgreen@email.com', '+1 (555) 101-0028', null, 'new', 'social', 'Instagram promotion responder', true),
('Ryan Adams', 'radams@email.com', '+1 (555) 101-0029', 'Adams Auto Repair', 'converted', 'website', 'Shop supplier - tires for customer cars', true),
('Elizabeth Baker', 'ebaker@email.com', '+1 (555) 101-0030', 'Baker Transport', 'contacted', 'phone', 'Fleet manager - requesting catalog', true),
('Nicholas Nelson', 'nnelson@email.com', '+1 (555) 101-0031', null, 'qualified', 'website', 'Off-road tires for Jeep', true),
('Victoria Carter', 'vcarter@email.com', '+1 (555) 101-0032', 'Carter Moving Co', 'new', 'referral', 'Moving truck fleet - 8 vehicles', true),
('Jonathan Mitchell', 'jmitchell@email.com', '+1 (555) 101-0033', null, 'closed', 'walk-in', 'Already purchased elsewhere', false),
('Rachel Roberts', 'rroberts@email.com', '+1 (555) 101-0034', 'Roberts Automotive', 'converted', 'website', 'Wholesale account - monthly orders', true),
('Austin Turner', 'aturner@email.com', '+1 (555) 101-0035', 'Turner Trucking', 'contacted', 'email', 'Requested quote for 10 trucks', true),
('Katherine Phillips', 'kphillips@email.com', '+1 (555) 101-0036', null, 'qualified', 'social', 'Facebook group member - tire advice', true),
('Justin Campbell', 'jcampbell@email.com', '+1 (555) 101-0037', 'Campbell Delivery', 'new', 'website', 'Needs delivery van tires', true),
('Morgan Parker', 'mparker@email.com', '+1 (555) 101-0038', null, 'contacted', 'phone', 'Follow-up needed - price quote', true),
('Dylan Evans', 'devans@email.com', '+1 (555) 101-0039', 'Evans Auto Sales', 'converted', 'referral', 'Buys tires for resale - dealership', true),
('Haley Edwards', 'hedwards@email.com', '+1 (555) 101-0040', 'Edwards Logistics', 'qualified', 'website', 'Fleet tires - 15 vehicles', true),
('Aaron Collins', 'acollins@email.com', '+1 (555) 101-0041', null, 'new', 'email', 'Inquiry about run-flat tires', true),
('Olivia Stewart', 'ostewart@email.com', '+1 (555) 101-0042', 'Stewart Auto Group', 'contacted', 'referral', 'Multi-location dealership - bulk pricing', true),
('Nathan Morris', 'nmorris@email.com', '+1 (555) 101-0043', null, 'qualified', 'website', 'All-terrain tires for pickup', true),
('Alexis Rogers', 'arogers@email.com', '+1 (555) 101-0044', 'Rogers Trucking', 'new', 'social', 'LinkedIn connection - fleet manager', true),
('Benjamin Reed', 'breed@email.com', '+1 (555) 101-0045', 'Reed Construction', 'closed', 'phone', 'Budget too low - no follow-up', false),
('Grace Cook', 'gcook@email.com', '+1 (555) 101-0046', null, 'converted', 'website', 'Bought tire and wheel package', true),
('Lucas Morgan', 'lmorgan@email.com', '+1 (555) 101-0047', 'Morgan Fleet Services', 'contacted', 'email', 'Requested fleet discount info', true),
('Taylor Bell', 'tbell@email.com', '+1 (555) 101-0048', null, 'qualified', 'walk-in', 'Walk-in - needs 4 tires installed', true),
('Caleb Murphy', 'cmurphy@email.com', '+1 (555) 101-0049', 'Murphy Auto Repair', 'new', 'referral', 'Shop owner - looking for supplier', true),
('Madison Bailey', 'mbailey@email.com', '+1 (555) 101-0050', 'Bailey Transport', 'converted', 'website', 'Fleet renewal - 20 vehicles', true),
('Connor Rivera', 'crivera@email.com', '+1 (555) 101-0051', null, 'qualified', 'phone', 'Price match request', true),
('Alexa Cooper', 'acooper@email.com', '+1 (555) 101-0052', 'Cooper Auto Body', 'contacted', 'website', 'Needs tires for customer cars', true),
('Sean Richardson', 'srichardson@email.com', '+1 (555) 101-0053', null, 'new', 'social', 'TikTok ad viewer - tire question', true),
('Alyssa Cox', 'acox@email.com', '+1 (555) 101-0054', 'Cox Delivery Services', 'qualified', 'referral', 'Delivery fleet - 6 vans', true),
('Trevor Howard', 'thoward@email.com', '+1 (555) 101-0055', 'Howard Trucking', 'converted', 'website', 'Repeat customer - semi-truck tires', true),
('Isabella Ward', 'iward@email.com', '+1 (555) 101-0056', null, 'contacted', 'email', 'Inquiry about performance tires', true),
('Devin Torres', 'dtorres@email.com', '+1 (555) 101-0057', 'Torres Auto Group', 'new', 'website', 'New dealership - needs supplier', true),
('Mackenzie Peterson', 'mpeterson@email.com', '+1 (555) 101-0058', null, 'qualified', 'walk-in', 'Walk-in - needs tires for SUV', true),
('Blake Gray', 'bgray@email.com', '+1 (555) 101-0059', 'Gray Fleet Management', 'converted', 'referral', 'Annual fleet contract signed', true),
('Sydney Ramirez', 'sramirez@email.com', '+1 (555) 101-0060', 'Ramirez Transport', 'new', 'social', 'Facebook ad responder', true),
('Cameron James', 'cjames@email.com', '+1 (555) 101-0061', null, 'contacted', 'phone', 'Cold call - interested in quote', true),
('Savannah Watson', 'swatson@email.com', '+1 (555) 101-0062', 'Watson Auto Repair', 'qualified', 'website', 'Looking for tire supplier for shop', true),
('Evan Brooks', 'ebrooks@email.com', '+1 (555) 101-0063', 'Brooks Logistics', 'new', 'email', 'Fleet quote for 25 vehicles', true),
('Kaitlyn Kelly', 'kkelly@email.com', '+1 (555) 101-0064', null, 'closed', 'walk-in', 'Not ready to buy', false),
('Logan Sanders', 'lsanders@email.com', '+1 (555) 101-0065', 'Sanders Automotive', 'converted', 'website', 'Monthly order - shop supplies', true),
('Brooke Price', 'bprice@email.com', '+1 (555) 101-0066', null, 'qualified', 'referral', 'Referred by existing customer', true),
('Jared Bennett', 'jbennett@email.com', '+1 (555) 101-0067', 'Bennett Trucking', 'contacted', 'phone', 'Interested in fleet program', true),
('Paige Wood', 'pwood@email.com', '+1 (555) 101-0068', 'Wood Transport', 'new', 'website', 'Needs tires for box trucks', true),
('Derek Barnes', 'dbarnes@email.com', '+1 (555) 101-0069', null, 'qualified', 'social', 'Instagram DM - tire sizes', true),
('Molly Ross', 'mross@email.com', '+1 (555) 101-0070', 'Ross Auto Sales', 'converted', 'referral', 'Used car dealer - bulk order', true),
('Marcus Henderson', 'mhenderson@email.com', '+1 (555) 101-0071', 'Henderson Fleet', 'contacted', 'email', 'Quote comparison requested', true),
('Kelsey Coleman', 'kcoleman@email.com', '+1 (555) 101-0072', null, 'new', 'website', 'Shopping for winter tires', true),
('Bradley Jenkins', 'bjenkins@email.com', '+1 (555) 101-0073', 'Jenkins Auto Care', 'qualified', 'walk-in', 'Walk-in - wants to become vendor', true),
('Vanessa Perry', 'vperry@email.com', '+1 (555) 101-0074', 'Perry Delivery Co', 'converted', 'website', 'Delivery fleet tires - repeat', true),
('Seth Powell', 'spowell@email.com', '+1 (555) 101-0075', null, 'new', 'social', 'YouTube ad click', true),
('Chelsea Long', 'clong@email.com', '+1 (555) 101-0076', 'Long Trucking', 'contacted', 'phone', 'Fleet manager - wants catalog', true),
('Wesley Patterson', 'wpatterson@email.com', '+1 (555) 101-0077', 'Patterson Logistics', 'qualified', 'referral', 'Needs 12 tires for fleet', true),
('Jasmine Hughes', 'jhughes@email.com', '+1 (555) 101-0078', null, 'new', 'website', 'First time visitor - tire quote', true),
('Luis Flores', 'lflores@email.com', '+1 (555) 101-0079', 'Flores Auto Body', 'converted', 'email', 'Shop owner - regular orders', true),
('Cassandra Washington', 'cwashington@email.com', '+1 (555) 101-0080', 'Washington Transport', 'contacted', 'website', 'Fleet tires - 8 vehicles', true),
('Jeremy Butler', 'jbutler@email.com', '+1 (555) 101-0081', null, 'qualified', 'phone', 'Callback requested - price quote', true),
('Bianca Simmons', 'bsimmons@email.com', '+1 (555) 101-0082', 'Simmons Auto Group', 'new', 'referral', 'Multiple dealership locations', true),
('Tanner Foster', 'tfoster@email.com', '+1 (555) 101-0083', null, 'closed', 'walk-in', 'Not interested - no reason', false),
('Breanna Gonzales', 'bgonzales@email.com', '+1 (555) 101-0084', 'Gonzales Trucking', 'converted', 'website', 'Repeat buyer - 6 months running', true),
('Patrick Bryant', 'pbryant@email.com', '+1 (555) 101-0085', 'Bryant Construction', 'qualified', 'email', 'Needs tires for heavy equipment', true),
('Monica Alexander', 'malexander@email.com', '+1 (555) 101-0086', null, 'new', 'social', 'Facebook group recommendation', true),
('Garrett Russell', 'grussell@email.com', '+1 (555) 101-0087', 'Russell Auto Repair', 'contacted', 'website', 'Shop supplier research', true),
('Tara Griffin', 'tgriffin@email.com', '+1 (555) 101-0088', 'Griffin Logistics', 'qualified', 'referral', 'Fleet manager - 30 vehicles', true),
('Shane Diaz', 'sdiaz@email.com', '+1 (555) 101-0089', null, 'new', 'phone', 'Inbound call - product inquiry', true),
('Christina Hayes', 'chayes@email.com', '+1 (555) 101-0090', 'Hayes Delivery', 'converted', 'website', 'Delivery fleet tires purchased', true),
('Eduardo Myers', 'emyers@email.com', '+1 (555) 101-0091', 'Myers Automotive', 'contacted', 'email', 'Wholesale inquiry', true),
('Shelby Ford', 'sford@email.com', '+1 (555) 101-0092', null, 'qualified', 'walk-in', 'Walk-in - compare tire brands', true),
('Jesse Hamilton', 'jhamilton@email.com', '+1 (555) 101-0093', 'Hamilton Trucking', 'new', 'social', 'LinkedIn ad responder', true),
('Erin Graham', 'egraham@email.com', '+1 (555) 101-0094', 'Graham Auto Sales', 'converted', 'referral', 'Dealership - buys in bulk', true),
('Dakota Sullivan', 'dsullivan@email.com', '+1 (555) 101-0095', null, 'contacted', 'website', 'Searched for tire deals', true),
('Heidi Wallace', 'hwallace@email.com', '+1 (555) 101-0096', 'Wallace Fleet Services', 'qualified', 'phone', 'Fleet renewal inquiry', true),
('Jonah Woods', 'jwoods@email.com', '+1 (555) 101-0097', 'Woods Transport', 'new', 'email', 'Quote for 18-wheeler fleet', true),
('Amber Cole', 'acole@email.com', '+1 (555) 101-0098', null, 'closed', 'walk-in', 'Price too high', false),
('Colin West', 'cwest@email.com', '+1 (555) 101-0099', 'West Auto Repair', 'converted', 'website', 'Monthly tire orders - shop', true),
('Rebecca Jordan', 'rjordan@email.com', '+1 (555) 101-0100', 'Jordan Logistics', 'qualified', 'referral', 'Fleet manager - requesting samples', true),
('Franklin Owens', 'fowens@email.com', '+1 (555) 101-0101', null, 'new', 'social', 'Instagram story viewer', true),
('Catherine Reynolds', 'creynolds@email.com', '+1 (555) 101-0102', 'Reynolds Auto Group', 'contacted', 'website', 'Multi-dealership inquiry', true),
('Micah Fisher', 'mfisher@email.com', '+1 (555) 101-0103', 'Fisher Trucking', 'qualified', 'phone', 'Call about fleet pricing', true),
('Hollie Ellis', 'hellis@email.com', '+1 (555) 101-0104', null, 'converted', 'website', 'Bought tire & rim package', true),
('Adrian Harrison', 'aharrison@email.com', '+1 (555) 101-0105', 'Harrison Delivery', 'new', 'email', 'Delivery van fleet - 4 vehicles', true),
('Kristen Marshall', 'kmarshall@email.com', '+1 (555) 101-0106', 'Marshall Auto Care', 'contacted', 'referral', 'Referred by Michelin rep', true),
('Miles Chapman', 'mchapman@email.com', '+1 (555) 101-0107', null, 'qualified', 'walk-in', 'Walk-in - performance tires', true),
('Destiny Hunt', 'dhunt@email.com', '+1 (555) 101-0108', 'Hunt Transport', 'new', 'website', 'Fleet quote - 10 trucks', true),
('Hector Webb', 'hwebb@email.com', '+1 (555) 101-0109', 'Webb Automotive', 'converted', 'social', 'Facebook ad - became customer', true),
('Caroline Tucker', 'ctucker@email.com', '+1 (555) 101-0110', null, 'closed', 'phone', 'Not calling back', false),
('Dustin Freeman', 'dfreeman@email.com', '+1 (555) 101-0111', 'Freeman Logistics', 'qualified', 'website', 'Large fleet - 50+ vehicles', true),
('Autumn Burns', 'aburns@email.com', '+1 (555) 101-0112', 'Burns Auto Sales', 'contacted', 'referral', 'Used car lot - monthly orders', true),
('Randy Gordon', 'rgordon@email.com', '+1 (555) 101-0113', null, 'new', 'email', 'Tire size compatibility question', true),
('Miranda Kelley', 'mkelley@email.com', '+1 (555) 101-0114', 'Kelley Fleet Services', 'qualified', 'website', 'Fleet winter tire program', true),
('Andre Lawrence', 'alawrence@email.com', '+1 (555) 101-0115', 'Lawrence Auto Repair', 'converted', 'phone', 'Shop owner - weekly orders', true),
('Jade Spencer', 'jspencer@email.com', '+1 (555) 101-0116', null, 'new', 'social', 'Twitter promotion click', true),
('Ricky Harper', 'rharper@email.com', '+1 (555) 101-0117', 'Harper Transport', 'contacted', 'walk-in', 'Walk-in - fleet brochure', true),
('Candice Lane', 'clane@email.com', '+1 (555) 101-0118', 'Lane Trucking', 'qualified', 'website', 'Quote for 15 trucks', true),
('Landon Gibson', 'lgibson@email.com', '+1 (555) 101-0119', null, 'new', 'referral', 'Friend referral - tire shopping', true),
('Shannon Armstrong', 'sarmstrong@email.com', '+1 (555) 101-0120', 'Armstrong Auto', 'converted', 'email', 'Email campaign - made purchase', true),
('Jermaine George', 'jgeorge@email.com', '+1 (555) 101-0121', 'George Fleet', 'contacted', 'phone', 'Fleet discount inquiry', true),
('Lydia Evans', 'levans@email.com', '+1 (555) 101-0122', null, 'qualified', 'website', 'All-season tire research', true),
('Travis Carter', 'tcarter@email.com', '+1 (555) 101-0123', 'Carter Delivery', 'new', 'social', 'YouTube recommendation', true),
('Anna Mitchell', 'amitchell@email.com', '+1 (555) 101-0124', 'Mitchell Logistics', 'closed', 'walk-in', 'Found local shop instead', false),
('Troy Martinez', 'tmartinez@email.com', '+1 (555) 101-0125', 'Martinez Auto Group', 'converted', 'referral', 'Bulk dealer order', true),
('Diana Roberts', 'droberts@email.com', '+1 (555) 101-0126', null, 'qualified', 'website', 'Performance tire inquiry', true),
('Corey Anderson', 'canderson@email.com', '+1 (555) 101-0127', 'Anderson Transport', 'contacted', 'email', 'Fleet quote needed', true),
('Christie Thomas', 'cthomas@email.com', '+1 (555) 101-0128', 'Thomas Auto Repair', 'new', 'phone', 'Callback from voicemail', true),
('Ian Jackson', 'ijackson@email.com', '+1 (555) 101-0129', null, 'converted', 'website', 'Bought winter tire set', true),
('Bridget White', 'bwhite@email.com', '+1 (555) 101-0130', 'White Trucking', 'qualified', 'referral', 'Referred by fleet manager', true),
('Nolan Harris', 'nharris@email.com', '+1 (555) 101-0131', 'Harris Fleet Services', 'contacted', 'social', 'LinkedIn conversation', true),
('Kendra Martin', 'kmartin@email.com', '+1 (555) 101-0132', null, 'new', 'website', 'Tire deal comparison', true),
('Mitchell Clark', 'mclark@email.com', '+1 (555) 101-0133', 'Clark Automotive', 'qualified', 'phone', 'Shop - wholesale pricing', true),
('Esmeralda Lewis', 'elewis@email.com', '+1 (555) 101-0134', 'Lewis Logistics', 'converted', 'email', 'Email campaign - fleet sale', true),
('Brett Walker', 'bwalker@email.com', '+1 (555) 101-0135', null, 'new', 'walk-in', 'Walk-in - needs installation', true),
('Tasha Hall', 'thall@email.com', '+1 (555) 101-0136', 'Hall Auto Sales', 'contacted', 'website', 'Dealership - tire sourcing', true),
('Karl Allen', 'kallen@email.com', '+1 (555) 101-0137', 'Allen Trucking', 'qualified', 'referral', 'Fleet manager referral', true),
('Alison Young', 'ayoung@email.com', '+1 (555) 101-0138', null, 'new', 'social', 'Facebook page visitor', true),
('Steve King', 'sking@email.com', '+1 (555) 101-0139', 'King Repair Shop', 'converted', 'website', 'Monthly tire orders', true),
('Meghan Wright', 'mwright@email.com', '+1 (555) 101-0140', 'Wright Delivery', 'contacted', 'phone', 'Delivery fleet inquiry', true),
('Gavin Hill', 'ghill@email.com', '+1 (555) 101-0141', null, 'qualified', 'email', 'Price quote comparison', true),
('Cassie Scott', 'cscott@email.com', '+1 (555) 101-0142', 'Scott Transport', 'new', 'website', 'First visit - browsing tires', true),
('Fernando Green', 'fgreen@email.com', '+1 (555) 101-0143', 'Green Logistics', 'closed', 'walk-in', 'Budget constraints', false),
('Kristina Adams', 'kadams@email.com', '+1 (555) 101-0144', 'Adams Auto Group', 'converted', 'referral', 'Repeat wholesale order', true),
('Rafael Baker', 'rbaker@email.com', '+1 (555) 101-0145', null, 'qualified', 'social', 'Instagram DM - tire sizes', true),
('Stacey Nelson', 'snelson@email.com', '+1 (555) 101-0146', 'Nelson Fleet', 'contacted', 'website', 'Fleet program enrollment', true),
('Phillip Carter', 'pcarter@email.com', '+1 (555) 101-0147', 'Carter Automotive', 'new', 'phone', 'Cold call - interested', true),
('Courtney Mitchell', 'cmitchell@email.com', '+1 (555) 101-0148', null, 'qualified', 'email', 'Inquiry about run-flat tires', true),
('Dale Roberts', 'droberts2@email.com', '+1 (555) 101-0149', 'Roberts Trucking', 'converted', 'website', 'Fleet renewal - 12 trucks', true),
('Ebony Turner', 'eturner@email.com', '+1 (555) 101-0150', 'Turner Auto Body', 'new', 'referral', 'Shop referral from supplier', true),
('Donnie Phillips', 'dphillips@email.com', '+1 (555) 101-0151', null, 'contacted', 'walk-in', 'Walk-in - tire repair', true),
('Felicia Campbell', 'fcampbell@email.com', '+1 (555) 101-0152', 'Campbell Logistics', 'qualified', 'website', 'Fleet tires - 20 vehicles', true),
('Mike Parker', 'mparker2@email.com', '+1 (555) 101-0153', 'Parker Auto Repair', 'new', 'social', 'Google ad click', true),
('Yolanda Evans', 'yevans@email.com', '+1 (555) 101-0154', null, 'converted', 'phone', 'Phone order placed', true),
('Eddie Edwards', 'eedwards@email.com', '+1 (555) 101-0155', 'Edwards Transport', 'contacted', 'email', 'Quote request - semi tires', true),
('Lauren Collins', 'lcollins@email.com', '+1 (555) 101-0156', 'Collins Fleet Services', 'qualified', 'referral', 'Fleet manager friend referral', true),
('Erica Stewart', 'estewart@email.com', '+1 (555) 101-0157', null, 'new', 'website', 'Searching for SUV tires', true),
('Gordon Morris', 'gmorris@email.com', '+1 (555) 101-0158', 'Morris Trucking', 'closed', 'phone', 'Already has supplier', false),
('Tracy Rogers', 'trogers@email.com', '+1 (555) 101-0159', 'Rogers Auto Sales', 'converted', 'website', 'Dealer bulk purchase', true),
('Darryl Reed', 'dreed@email.com', '+1 (555) 101-0160', null, 'qualified', 'social', 'Facebook group post - tire questions', true),
('Lacey Cook', 'lcook@email.com', '+1 (555) 101-0161', 'Cook Delivery', 'contacted', 'walk-in', 'Walk-in - delivery van tires', true),
('Clifford Morgan', 'cmorgan@email.com', '+1 (555) 101-0162', 'Morgan Logistics', 'new', 'website', 'Fleet inquiry - 8 vans', true),
('Jillian Bell', 'jbell@email.com', '+1 (555) 101-0163', null, 'qualified', 'email', 'New customer - tire help', true),
('Roderick Murphy', 'rmurphy@email.com', '+1 (555) 101-0164', 'Murphy Auto Group', 'converted', 'referral', 'Dealership chain - big order', true),
('Deanna Bailey', 'dbailey@email.com', '+1 (555) 101-0165', 'Bailey Auto Repair', 'contacted', 'phone', 'Shop - wholesale inquiry', true),
('Santiago Rivera', 'srivera@email.com', '+1 (555) 101-0166', null, 'new', 'website', 'Performance tire shopping', true),
('Kellie Cooper', 'kcooper@email.com', '+1 (555) 101-0167', 'Cooper Transport', 'qualified', 'social', 'Instagram influencer referral', true),
('Hugh Richardson', 'hrichardson@email.com', '+1 (555) 101-0168', 'Richardson Fleet', 'contacted', 'email', 'Fleet quote follow-up', true),
('Toni Cox', 'tcox@email.com', '+1 (555) 101-0169', null, 'converted', 'walk-in', 'Walk-in - bought tires on spot', true),
('Brad Howard', 'bhoward@email.com', '+1 (555) 101-0170', 'Howard Logistics', 'new', 'referral', 'Referred by vendor', true),
('Selena Ward', 'sward@email.com', '+1 (555) 101-0171', 'Ward Delivery Co', 'qualified', 'website', 'Delivery fleet - 5 vehicles', true),
('Marty Torres', 'mtorres@email.com', '+1 (555) 101-0172', null, 'contacted', 'phone', 'Phone inquiry - all-season', true),
('Elena Peterson', 'epeterson@email.com', '+1 (555) 101-0173', 'Peterson Auto', 'new', 'email', 'Tire warranty question', true),
('Duane Gray', 'dgray@email.com', '+1 (555) 101-0174', 'Gray Trucking', 'closed', 'walk-in', 'Went with competitor', false),
('Janet Ramirez', 'jramirez@email.com', '+1 (555) 101-0175', 'Ramirez Auto Body', 'converted', 'website', 'Shop order - customer tires', true),
('Terrence James', 'tjames@email.com', '+1 (555) 101-0176', null, 'qualified', 'social', 'Twitter follower - tire advice', true),
('Glenda Watson', 'gwatson@email.com', '+1 (555) 101-0177', 'Watson Fleet', 'contacted', 'referral', 'Fleet referral - 15 trucks', true),
('Kirk Brooks', 'kbrooks@email.com', '+1 (555) 101-0178', 'Brooks Automotive', 'new', 'website', 'Shop - needs supplier', true),
('Sherri Kelly', 'skelly@email.com', '+1 (555) 101-0179', null, 'qualified', 'phone', 'Callback - price match', true),
('Bernard Sanders', 'bsanders@email.com', '+1 (555) 101-0180', 'Sanders Transport', 'converted', 'email', 'Email promotion - fleet order', true),
('Darlene Price', 'dprice@email.com', '+1 (555) 101-0181', 'Price Auto Sales', 'contacted', 'walk-in', 'Walk-in - dealership inquiry', true),
('Roland Bennett', 'rbennett@email.com', '+1 (555) 101-0182', null, 'new', 'website', 'Off-road tire research', true),
('Tia Wood', 'twood@email.com', '+1 (555) 101-0183', 'Wood Logistics', 'qualified', 'referral', 'Fleet manager - 25 vehicles', true),
('Sammy Barnes', 'sbarnes@email.com', '+1 (555) 101-0184', 'Barnes Auto Repair', 'converted', 'social', 'Facebook ad - regular customer', true),
('Loretta Ross', 'lross@email.com', '+1 (555) 101-0185', null, 'new', 'phone', 'Incoming call - tire sizes', true),
('Alberto Henderson', 'ahenderson@email.com', '+1 (555) 101-0186', 'Henderson Trucking', 'contacted', 'email', 'Fleet quote emailed', true),
('Pamela Coleman', 'pcoleman@email.com', '+1 (555) 101-0187', 'Coleman Delivery', 'qualified', 'website', 'Delivery fleet - 10 vans', true),
('Gilbert Jenkins', 'gjenkins@email.com', '+1 (555) 101-0188', null, 'new', 'walk-in', 'Walk-in - browsing', true),
('Bridgette Perry', 'bperry@email.com', '+1 (555) 101-0189', 'Perry Auto Group', 'closed', 'referral', 'Too expensive', false),
('Armando Powell', 'apowell@email.com', '+1 (555) 101-0190', 'Powell Fleet', 'converted', 'website', 'Fleet winter tire order', true),
('Roxanne Long', 'rlong@email.com', '+1 (555) 101-0191', null, 'qualified', 'social', 'YouTube subscriber - tire tips', true),
('Emmett Patterson', 'epatterson@email.com', '+1 (555) 101-0192', 'Patterson Auto', 'contacted', 'phone', 'Shop - wants demo', true),
('Tara Hughes', 'thughes@email.com', '+1 (555) 101-0193', 'Hughes Logistics', 'new', 'email', 'Price quote for 18-wheelers', true),
('Bryant Flores', 'bflores@email.com', '+1 (555) 101-0194', null, 'qualified', 'website', 'Tire comparison - 3 brands', true),
('Carrie Washington', 'cwashington2@email.com', '+1 (555) 101-0195', 'Washington Transport', 'converted', 'referral', 'Repeat fleet order', true),
('Damon Butler', 'dbutler@email.com', '+1 (555) 101-0196', 'Butler Automotive', 'contacted', 'walk-in', 'Walk-in - shop owner', true),
('Stacie Simmons', 'ssimmons@email.com', '+1 (555) 101-0197', null, 'new', 'social', 'Pinterest ad click', true),
('Tommy Foster', 'tfoster2@email.com', '+1 (555) 101-0198', 'Foster Trucking', 'qualified', 'phone', 'Callback - fleet renewal', true),
('Gwendolyn Gonzalez', 'ggonzalez@email.com', '+1 (555) 101-0199', 'Gonzalez Auto', 'converted', 'website', 'Customer - 2nd purchase', true),
('Leslie Bryant', 'lbryant@email.com', '+1 (555) 101-0200', 'Bryant Delivery', 'new', 'email', 'Delivery inquiry', true),
('Marshall Alexander', 'malexander2@email.com', '+1 (555) 101-0201', null, 'contacted', 'referral', 'Friend referral', true),
('Claudia Russell', 'crussell@email.com', '+1 (555) 101-0202', 'Russell Logistics', 'qualified', 'website', 'Fleet - 12 trucks', true),
('Salvatore Griffin', 'sgriffin@email.com', '+1 (555) 101-0203', 'Griffin Auto Group', 'new', 'social', 'Instagram ad visitor', true),
('Deidre Diaz', 'ddiaz@email.com', '+1 (555) 101-0204', null, 'closed', 'phone', 'Not interested - budget', false),
('Arturo Hayes', 'ahayes@email.com', '+1 (555) 101-0205', 'Hayes Trucking', 'converted', 'website', 'Fleet upgrade - 20 tires', true),
('Jeanette Myers', 'jmyers@email.com', '+1 (555) 101-0206', 'Myers Auto Repair', 'contacted', 'walk-in', 'Walk-in - shop supplier', true),
('Neal Ford', 'nford@email.com', '+1 (555) 101-0207', null, 'qualified', 'email', 'Comparing tire prices', true),
('Kristy Hamilton', 'khamilton@email.com', '+1 (555) 101-0208', 'Hamilton Fleet', 'new', 'website', 'Fleet inquiry - 6 vehicles', true),
('Ricky Graham', 'rgraham@email.com', '+1 (555) 101-0209', 'Graham Auto Sales', 'converted', 'referral', 'Dealer - monthly bulk order', true),
('Marlene Sullivan', 'msullivan@email.com', '+1 (555) 101-0210', null, 'qualified', 'social', 'Facebook group member', true),
('Herman Wallace', 'hwallace2@email.com', '+1 (555) 101-0211', 'Wallace Transport', 'contacted', 'phone', 'Fleet discount call', true),
('Lee Woods', 'lwoods@email.com', '+1 (555) 101-0212', 'Woods Automotive', 'new', 'website', 'Tire installation quote', true),
('Ramona Cole', 'rcole@email.com', '+1 (555) 101-0213', null, 'qualified', 'email', 'Quote for 4 tires', true),
('Clayton West', 'cwest2@email.com', '+1 (555) 101-0214', 'West Logistics', 'converted', 'walk-in', 'Walk-in - bought tires', true),
('Sonya Jordan', 'sjordan@email.com', '+1 (555) 101-0215', 'Jordan Fleet Services', 'contacted', 'referral', 'Fleet manager referral program', true),
('Perry Owens', 'powens@email.com', '+1 (555) 101-0216', null, 'new', 'social', 'TikTok ad view', true),
('Deana Reynolds', 'dreynolds@email.com', '+1 (555) 101-0217', 'Reynolds Trucking', 'qualified', 'phone', 'Call about tire promotion', true),
('Byron Fisher', 'bfisher@email.com', '+1 (555) 101-0218', 'Fisher Auto Body', 'converted', 'website', 'Shop order placed', true),
('John Ellis', 'jellis@email.com', '+1 (555) 101-0219', null, 'new', 'email', 'Price check - winter tires', true),
('Kari Harrison', 'kharrison@email.com', '+1 (555) 101-0220', 'Harrison Auto Repair', 'contacted', 'walk-in', 'Walk-in - wanted catalog', true),
('Lyle Marshall', 'lmarshall@email.com', '+1 (555) 101-0221', 'Marshall Logistics', 'qualified', 'referral', 'Fleet referral - 30 trucks', true),
('Tammie Chapman', 'tchapman@email.com', '+1 (555) 101-0222', null, 'new', 'website', 'First time visitor', true),
('Dwight Hunt', 'dhunt2@email.com', '+1 (555) 101-0223', 'Hunt Auto Sales', 'closed', 'social', 'Not responding', false),
('Krista Webb', 'kwebb@email.com', '+1 (555) 101-0224', 'Webb Transport', 'converted', 'phone', 'Phone order - 6 tires', true),
('Forrest Tucker', 'ftucker@email.com', '+1 (555) 101-0225', null, 'qualified', 'email', 'Fleet inquiry - 15 trucks', true),
('Shelley Freeman', 'sfreeman@email.com', '+1 (555) 101-0226', 'Freeman Auto', 'contacted', 'website', 'Shop - wholesale pricing', true),
('Guillermo Burns', 'gburns@email.com', '+1 (555) 101-0227', 'Burns Fleet', 'new', 'referral', 'Referred by existing fleet client', true),
('Tricia Gordon', 'tgordon@email.com', '+1 (555) 101-0228', null, 'qualified', 'walk-in', 'Walk-in - tire question', true),
('Kurt Kelley', 'kkelley@email.com', '+1 (555) 101-0229', 'Kelley Auto Group', 'converted', 'website', 'Dealer network signup', true),
('Beverly Lawrence', 'blawrence@email.com', '+1 (555) 101-0230', 'Lawrence Trucking', 'contacted', 'phone', 'Fleet quote needed', true),
('Dwayne Spencer', 'dspencer@email.com', '+1 (555) 101-0231', null, 'new', 'social', 'Google ad click', true),
('Louise Harper', 'lharper@email.com', '+1 (555) 101-0232', 'Harper Logistics', 'qualified', 'email', 'Quote for delivery fleet', true),
('Ramon Lane', 'rlane@email.com', '+1 (555) 101-0233', 'Lane Automotive', 'converted', 'referral', 'Referral from Michelin', true),
('Krystal Gibson', 'kgibson@email.com', '+1 (555) 101-0234', null, 'new', 'website', 'Searching for tire deals', true),
('Darren Armstrong', 'darmstrong@email.com', '+1 (555) 101-0235', 'Armstrong Fleet Services', 'contacted', 'walk-in', 'Walk-in - fleet inquiry', true),
('Dixie George', 'dgeorge@email.com', '+1 (555) 101-0236', 'George Auto Repair', 'qualified', 'phone', 'Shop - wants to stock tires', true),
('Sandy Crawford', 'scrawford@email.com', '+1 (555) 101-0237', null, 'new', 'social', 'Facebook page like', true),
('Johnnie Murray', 'jmurray@email.com', '+1 (555) 101-0238', 'Murray Transport', 'converted', 'website', 'Online order - fleet tires', true),
('Janice Bishop', 'jbishop@email.com', '+1 (555) 101-0239', 'Bishop Auto Sales', 'contacted', 'email', 'Dealer inquiry - bulk pricing', true),
('Leroy Kim', 'lkim@email.com', '+1 (555) 101-0240', null, 'qualified', 'referral', 'Referral from shop owner', true),
('Betsy Cox', 'bcox@email.com', '+1 (555) 101-0241', 'Cox Fleet Services', 'new', 'website', 'Fleet inquiry - 10 vehicles', true),
('Moses Howard', 'mhoward@email.com', '+1 (555) 101-0242', 'Howard Trucking', 'closed', 'phone', 'Not interested', false),
('Lena Ward', 'lward@email.com', '+1 (555) 101-0243', null, 'converted', 'website', 'Bought performance tires', true),
('Jonathon Torres', 'jtorres@email.com', '+1 (555) 101-0244', 'Torres Logistics', 'contacted', 'social', 'LinkedIn ad responder', true),
('Mindy Peterson', 'mpeterson2@email.com', '+1 (555) 101-0245', 'Peterson Auto Repair', 'qualified', 'email', 'Shop - wants to be vendor', true),
('Gustavo Gray', 'ggray@email.com', '+1 (555) 101-0246', null, 'new', 'walk-in', 'Walk-in - needs tire repair', true),
('Dolores Ramirez', 'dramirez@email.com', '+1 (555) 101-0247', 'Ramirez Fleet', 'converted', 'referral', 'Fleet renewal - annual contract', true),
('Benny James', 'bjames@email.com', '+1 (555) 101-0248', 'James Automotive', 'contacted', 'phone', 'Call about shop program', true),
('Katie Watson', 'kwatson@email.com', '+1 (555) 101-0249', null, 'qualified', 'website', 'Researching tire brands', true),
('Boyd Brooks', 'bbrooks@email.com', '+1 (555) 101-0250', 'Brooks Delivery', 'new', 'social', 'YouTube ad click', true),
('Alexis Kelly', 'akelly@email.com', '+1 (555) 101-0251', 'Kelly Auto Group', 'converted', 'email', 'Email campaign - made purchase', true),
('Stuart Sanders', 'ssanders@email.com', '+1 (555) 101-0252', null, 'contacted', 'referral', 'Customer referral', true),
('Bethany Price', 'bprice2@email.com', '+1 (555) 101-0253', 'Price Transport', 'qualified', 'website', 'Fleet pricing request', true),
('Willie Bennett', 'wbennett@email.com', '+1 (555) 101-0254', 'Bennett Auto Body', 'new', 'phone', 'Voicemail - call back', true),
('Rosemary Wood', 'rwood@email.com', '+1 (555) 101-0255', null, 'closed', 'walk-in', 'Never came back', false),
('Freddy Barnes', 'fbarnes@email.com', '+1 (555) 101-0256', 'Barnes Logistics', 'converted', 'website', 'Bought winter tires', true),
('Misty Ross', 'mross2@email.com', '+1 (555) 101-0257', 'Ross Fleet Services', 'contacted', 'social', 'Twitter conversation', true),
('Alfonso Henderson', 'ahenderson2@email.com', '+1 (555) 101-0258', 'Henderson Auto', 'qualified', 'email', 'Shop - tire pricing', true),
('Susanne Coleman', 'scoleman@email.com', '+1 (555) 101-0259', null, 'new', 'referral', 'Friend recommendation', true),
('Marcus Jenkins', 'mjenkins@email.com', '+1 (555) 101-0260', 'Jenkins Trucking', 'converted', 'website', 'Repeat order - fleet', true),
('Lakisha Perry', 'lperry@email.com', '+1 (555) 101-0261', 'Perry Auto Sales', 'contacted', 'phone', 'Call back - dealership pricing', true),
('Travis Powell', 'tpowell@email.com', '+1 (555) 101-0262', null, 'qualified', 'walk-in', 'Walk-in - lifted truck tires', true),
('Mandi Long', 'mlong@email.com', '+1 (555) 101-0263', 'Long Transport', 'new', 'website', 'Fleet inquiry - 18 wheelers', true),
('Jake Patterson', 'jpatterson@email.com', '+1 (555) 101-0264', 'Patterson Auto Group', 'contacted', 'email', 'Dealership chain inquiry', true),
('Summer Hughes', 'shughes@email.com', '+1 (555) 101-0265', null, 'qualified', 'social', 'Instagram contest winner', true),
('Curtis Flores', 'cflores@email.com', '+1 (555) 101-0266', 'Flores Logistics', 'converted', 'referral', 'Fleet referral - 8 trucks', true),
('Heather Washington', 'hwashington@email.com', '+1 (555) 101-0267', 'Washington Auto', 'new', 'website', 'Tire warranty question', true),
('Adam Butler', 'abutler@email.com', '+1 (555) 101-0268', null, 'contacted', 'phone', 'Incoming call - pricing', true),
('Kathryn Simmons', 'ksimmons@email.com', '+1 (555) 101-0269', 'Simmons Fleet', 'qualified', 'email', 'Fleet quote requested', true),
('Omar Foster', 'ofoster@email.com', '+1 (555) 101-0270', 'Foster Repair', 'converted', 'walk-in', 'Walk-in - becoming regular', true),
('Tonia Gonzalez', 'tgonzalez@email.com', '+1 (555) 101-0271', null, 'new', 'referral', 'Shop referral', true),
('Earnest Bryant', 'ebryant@email.com', '+1 (555) 101-0272', 'Bryant Trucking', 'closed', 'social', 'Not interested - price', false),
('Sheryl Alexander', 'salexander@email.com', '+1 (555) 101-0273', 'Alexander Auto Body', 'converted', 'website', 'Customer - 3rd purchase', true),
('Karl Russell', 'krussell@email.com', '+1 (555) 101-0274', null, 'qualified', 'phone', 'Call about all-terrain tires', true),
('Dianna Griffin', 'dgriffin@email.com', '+1 (555) 101-0275', 'Griffin Transport', 'contacted', 'email', 'Fleet discount program', true),
('Efrain Diaz', 'ediaz@email.com', '+1 (555) 101-0276', 'Diaz Auto Repair', 'new', 'website', 'Shop - wants catalog', true),
('Nora Hayes', 'nhayes@email.com', '+1 (555) 101-0277', null, 'qualified', 'walk-in', 'Walk-in - tire change', true),
('Erik Myers', 'emyers2@email.com', '+1 (555) 101-0278', 'Myers Logistics', 'converted', 'referral', 'Fleet renewal - 22 trucks', true),
('Lorraine Ford', 'lford@email.com', '+1 (555) 101-0279', 'Ford Automotive', 'contacted', 'social', 'Facebook ad inquiry', true),
('Darrin Hamilton', 'dhamilton@email.com', '+1 (555) 101-0280', null, 'new', 'website', 'Performance tire inquiry', true),
('Elaine Graham', 'egraham2@email.com', '+1 (555) 101-0281', 'Graham Fleet', 'qualified', 'phone', 'Callback - fleet pricing', true),
('Terry Sullivan', 'tsullivan@email.com', '+1 (555) 101-0282', 'Sullivan Auto Sales', 'converted', 'email', 'Bulk dealer order', true),
('Brandi Wallace', 'bwallace@email.com', '+1 (555) 101-0283', null, 'new', 'referral', 'Referred by tire shop', true),
('Cedric Woods', 'cwoods@email.com', '+1 (555) 101-0284', 'Woods Transport', 'contacted', 'website', 'Fleet manager inquiry', true),
('Rochelle Cole', 'rcole2@email.com', '+1 (555) 101-0285', 'Cole Auto Repair', 'qualified', 'walk-in', 'Walk-in - shop pricing', true),
('Alvin West', 'awest@email.com', '+1 (555) 101-0286', null, 'new', 'social', 'Snapchat ad', true),
('Christa Jordan', 'cjordan@email.com', '+1 (555) 101-0287', 'Jordan Logistics', 'closed', 'phone', 'Not returning calls', false),
('Nelson Owens', 'nowens@email.com', '+1 (555) 101-0288', 'Owens Fleet Services', 'converted', 'email', 'Fleet deal closed', true),
('Mable Reynolds', 'mreynolds@email.com', '+1 (555) 101-0289', null, 'qualified', 'referral', 'Friend of fleet manager', true),
('Lionel Fisher', 'lfisher@email.com', '+1 (555) 101-0290', 'Fisher Auto Group', 'contacted', 'website', 'Dealer network inquiry', true),
('Edna Ellis', 'eellis@email.com', '+1 (555) 101-0291', 'Ellis Trucking', 'new', 'social', 'LinkedIn post viewer', true),
('Rex Harrison', 'rharrison@email.com', '+1 (555) 101-0292', null, 'qualified', 'phone', 'Phone - performance tires', true),
('Jeannie Marshall', 'jmarshall@email.com', '+1 (555) 101-0293', 'Marshall Auto', 'converted', 'walk-in', 'Walk-in - became customer', true),
('Hubert Chapman', 'hchapman@email.com', '+1 (555) 101-0294', 'Chapman Logistics', 'contacted', 'email', 'Fleet quote comparison', true),
('Vickie Hunt', 'vhunt@email.com', '+1 (555) 101-0295', null, 'new', 'website', 'SUV tire research', true),
('Randal Webb', 'rwebb@email.com', '+1 (555) 101-0296', 'Webb Delivery', 'qualified', 'referral', 'Referral from existing', true),
('Tammy Tucker', 'ttucker@email.com', '+1 (555) 101-0297', 'Tucker Auto Body', 'converted', 'social', 'Instagram promo - purchased', true),
('Teddy Freeman', 'tfreeman@email.com', '+1 (555) 101-0298', null, 'new', 'phone', 'Cold call - interested', true),
('Angie Burns', 'aburns2@email.com', '+1 (555) 101-0299', 'Burns Trucking', 'contacted', 'website', 'Fleet renewal - 12 trucks', true),
('Marlon Gordon', 'mgordon@email.com', '+1 (555) 101-0300', 'Gordon Auto Repair', 'qualified', 'email', 'Shop - tire supplier', true),
('Sonia Kelley', 'skelley@email.com', '+1 (555) 101-0301', null, 'new', 'walk-in', 'Walk-in - browsing tires', true),
('%TestUser%', 'testuser@example.com', '+1 (555) 000-0000', 'Test Company', 'new', 'website', 'Test lead for development', true);
