import type { Promotion } from "./types";

export const PROMOTIONS: Promotion[] = [
  {
    id: "buy-4-tires",
    name: "Buy 4 Tires, Save $100",
    description: "Save $100 when you purchase 4 or more tires",
    type: "bundle_tires",
    value: 100,
    stackable: true,
    priority: 10,
    badgeText: "Buy 4 Save $100",
    badgeColor: "bg-blue-600",
  },
  {
    id: "free-shipping-over-200",
    name: "Free Shipping",
    description: "Free shipping on orders over $200",
    type: "free_shipping",
    value: 0,
    minSubtotal: 200,
    stackable: true,
    priority: 1,
    badgeText: "Free Shipping",
    badgeColor: "bg-green-600",
  },
  {
    id: "winter-sale",
    name: "Winter Tire Sale",
    description: "20% off all winter tires",
    type: "category",
    value: 20,
    categorySlug: "winter",
    stackable: false,
    priority: 5,
    badgeText: "Winter Sale",
    badgeColor: "bg-sky-600",
  },
  {
    id: "summer-event",
    name: "Summer Tire Event",
    description: "15% off all summer tires",
    type: "category",
    value: 15,
    categorySlug: "summer",
    stackable: false,
    priority: 5,
    badgeText: "Summer Event",
    badgeColor: "bg-orange-600",
  },
  {
    id: "wheel-clearance",
    name: "Wheel Clearance",
    description: "25% off all alloy wheels",
    type: "category",
    value: 25,
    categorySlug: "alloy-wheels",
    stackable: false,
    priority: 5,
    badgeText: "Clearance",
    badgeColor: "bg-red-600",
  },
  {
    id: "michelin-promo",
    name: "Michelin Manufacturer Offer",
    description: "10% off Michelin tires",
    type: "brand",
    value: 10,
    brandName: "Michelin",
    stackable: true,
    priority: 8,
    badgeText: "Manufacturer Offer",
    badgeColor: "bg-purple-600",
  },
  {
    id: "accessory-bundle",
    name: "Accessory Bundle & Save",
    description: "Save 15% on wheel & tire accessory bundles",
    type: "category",
    value: 15,
    categorySlug: "wheel-accessories",
    stackable: false,
    priority: 5,
    badgeText: "Bundle & Save",
    badgeColor: "bg-amber-600",
  },
  {
    id: "total-percentage",
    name: "Flash Sale: 20% Off",
    description: "20% off your entire purchase — limited time!",
    type: "flash_sale",
    value: 20,
    minSubtotal: 100,
    stackable: false,
    priority: 3,
    badgeText: "Limited Time",
    badgeColor: "bg-red-500",
  },
  {
    id: "clearance-items",
    name: "Clearance: Up to 30% Off",
    description: "30% off clearance-eligible items",
    type: "clearance",
    value: 30,
    stackable: true,
    priority: 15,
    badgeText: "Clearance",
    badgeColor: "bg-red-700",
  },
  {
    id: "winter-package",
    name: "Winter Package Deal",
    description: "Save $200 on winter tire & wheel packages",
    type: "category",
    value: 200,
    categorySlug: "packages",
    stackable: false,
    priority: 4,
    badgeText: "Package Deal",
    badgeColor: "bg-indigo-600",
  },
  {
    id: "seasonal-wheels",
    name: "Steel Wheel Special",
    description: "$50 off steel wheel sets",
    type: "category",
    value: 50,
    categorySlug: "steel-wheels",
    stackable: false,
    priority: 6,
    badgeText: "Wheel Special",
    badgeColor: "bg-teal-600",
  },
];

export const ANNOUNCEMENT_BAR = {
  text: "🔥 Free shipping on orders over $200 | Buy 4 Tires, Save $100 | Winter Tire Sale — 20% Off",
  cta: { label: "Shop Deals", href: "/shop" },
};

export const HOMEPAGE_DEALS_SECTION = {
  title: "Featured Deals",
  description: "Limited-time offers on premium tires, wheels, and accessories",
};
